### PR TITLE
servant-server: Fix build on GHC 9.2.1

### PR DESCRIPTION
**Pull request by k0001**
The issue is similar to the one in #1513:

```
src/Servant/Server/Internal.hs:824:10: error:
    • Uninferrable type variable k0 in
      type family equation right-hand side: (TypeError ...)
    • In the type instance declaration for ‘ServerT’
      In the instance declaration for
        ‘HasServer ((arr :: a -> b) :> sub) context’
    |
824 |     type ServerT (arr :> sub) _ = TypeError (PartialApplication HasServer arr)
    |
```

This fix is similar to the one in #1514.

### CODE REVIEW

**Comment by ysangkok** [comment]
I think it is good idea to apply smaller patches like this instead of a giant PR with lots of `allow-newer`.

**Comment by gdeest** [comment]
Thanks !
