### ISSUE TITLE
Error on build on case-insensitive-1.2.1.0

### ISSUE THREAD

**Issue by wadouk** [haskell-servant/servant#1209]
Hello, 

I'm fully new to haskell. I get this error when trying to start the tutorial.

```
Building library for case-insensitive-1.2.1.0..
[1 of 3] Compiling Data.CaseInsensitive.Internal ( Data/CaseInsensitive/Internal.hs, dist/build/Data/CaseInsensitive/Internal.o )

Data/CaseInsensitive/Internal.hs:69:1: error:
    Could not find module ‘Data.Hashable’
    There are files missing in the ‘hashable-1.2.7.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
69 | import Data.Hashable ( Hashable, hashWithSalt )
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build case-insensitive-1.2.1.0 (which is required by
test:spec from tutorial-0.10). See the build log above for details.

```

I use manjaro (arch linux), cabal-install 2.4.0.0 from official arch repo, ghc 8.6.5 staticaly linked (from ghc-static of official arch repo).

Tried to install manually hashable-1.2.7.0 and it exit as 0 but case-insensitive-1.2.1.0 exit as 1

Thanks for your help.

**Comment by phadej** [comment]
I'd recommend reading through https://wiki.archlinux.org/index.php/Haskell, in short this is problem with how Arch Linux packages Haskell tools, and to my knowledge that wiki page is the best resource.
