### ISSUE TITLE
Test suite fails to build with hspec-wai-0.8.0

### ISSUE THREAD

**Issue by DanBurton** [haskell-servant/servant#643]
There's been a change to the type of `matchBody`, from `Maybe ByteString` to `MatchBody`, causing the following type errors:

```
/Users/danburton/scratch/servant-server-0.9.1.1/test/Servant/Server/ErrorSpec.hs:214:44: error:
    • Couldn't match expected type ‘MatchBody’
                  with actual type ‘Maybe BCL.ByteString’
    • In the ‘matchBody’ field of a record
      In the second argument of ‘shouldRespondWith’, namely
        ‘200 {matchBody = Just $ encode (8 :: Int)}’
      In a stmt of a 'do' block:
        request methodPost "" [jsonCT, jsonAccept] jsonBody
        `shouldRespondWith` 200 {matchBody = Just $ encode (8 :: Int)}

/Users/danburton/scratch/servant-server-0.9.1.1/test/Servant/Server/ErrorSpec.hs:218:44: error:
    • Couldn't match expected type ‘MatchBody’
                  with actual type ‘Maybe BCL.ByteString’
    • In the ‘matchBody’ field of a record
      In the second argument of ‘shouldRespondWith’, namely
        ‘200 {matchBody = Just $ encode (4 :: Int)}’
      In a stmt of a 'do' block:
        request methodGet "a" [jsonCT, jsonAccept] jsonBody
        `shouldRespondWith` 200 {matchBody = Just $ encode (4 :: Int)}
```

How I reproduced this error:

```bash
$ stack unpack servant-server-0.9.1.1
$ cd servant-server-0.9.1.1/
<< add custom stack.yaml >>
$ stack test
```

```yaml
# stack.yaml
resolver: nightly-2016-11-22
extra-deps:
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- hspec-wai-0.8.0
- call-stack-0.1.0
```

**Comment by phadej** [comment]
IIRC this is fixed in `master`

**Comment by phadej** [comment]
Verified. Will be fixed in 0.10
