### ISSUE TITLE
Fails to build on ghc 9.2.1

### ISSUE THREAD

**Issue by danwdart** [haskell-servant/servant#1496]
It's related to the FlexibleContexts bug that got fixed. E.g.:

```
[ 4 of 31] Compiling Servant.API.ContentTypes ( src/Servant/API/ContentTypes.hs, dist/build/Servant/API/ContentTypes.o, dist/build/Servant/API/ContentTypes.dyn_o )

src/Servant/API/ContentTypes.hs:185:10: error:
    • Non type-variable argument
        in the constraint: AllMimeRender (ct : cts) a
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘AllCTRender (ct : cts) a’
    |
185 |          (Accept ct, AllMime cts, AllMimeRender (ct ': cts) a) => AllCTRender (ct ': cts) a where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Servant/API/ContentTypes.hs:281:10: error:
    • Non type-variable argument
        in the constraint: AllMimeRender (ctyp' : ctyps) a
      (Use FlexibleContexts to permit this)
    • In the instance declaration for
        ‘AllMimeRender (ctyp : ctyp' : ctyps) a’
    |
281 |          ( MimeRender ctyp a
    |          ^^^^^^^^^^^^^^^^^^^...

src/Servant/API/ContentTypes.hs:302:10: error:
    • Non type-variable argument
        in the constraint: AllMime (ctyp : ctyp' : ctyps)
      (Use FlexibleContexts to permit this)
    • In the instance declaration for
        ‘AllMimeRender (ctyp : ctyp' : ctyps) NoContent’
    |
302 |          ( AllMime (ctyp ': ctyp' ': ctyps)
```

**Comment by georgefst** [comment]
See #1482

**Comment by danwdart** [comment]
Thanks for updating!
