### ISSUE TITLE
Compilation: Servant.API.QueryString does not export DecodedQuery

### ISSUE THREAD

**Issue by kiefernforst** [haskell-servant/servant#1909]
I'm trying to compile servant-server https://github.com/haskell-servant/servant/commit/ddf13871b88d0787a478575350b31cef2bc6c60c against a git version of servant from yesterday with GHC 9.6.7 leading to:

```
[12 of 19] Compiling Servant.Server.Internal

src/Servant/Server/Internal.hs:134:33: error:
    Module ‘Servant.API.QueryString’ does not export ‘DecodedQuery’
    |
134 | import Servant.API.QueryString (DecodedQuery, FromDeepQuery (..))
    |                                 ^^^^^^^^^^^^

```

probably broken by https://github.com/haskell-servant/servant/pull/1901/changes
